[models.logistic]
name = "logistic"
batch_size = 128
learning_rate = 1e-3
seq_len = 256
weight_decay = 1e-4
num_categories = 83
pos_weight_threshold = 4.0

[models.nn]
name = "nn"
batch_size = 128
learning_rate = 2e-4
seq_len = 256
weight_decay = 4e-1
num_categories = 83
pos_weight_threshold = 4.0

[models.distil_bert]
name = "distil_bert"
pretrained = "distilbert-base-uncased"
batch_size = 32
learning_rate = 5e-5
max_length = 256                       # 512 is the max length for distilbert
num_categories = 83
