[models.logistic]
name = "logistic"
num_words = 30000
batch_size = 128
learning_rate = 0.001
max_length = 1000
weight_decay = 1e-5
num_categories = 83

[models.nn]
name = "nn"
num_words = 30000
batch_size = 128
learning_rate = 0.0005
max_length = 1000
weight_decay = 4e-1
num_categories = 83
