[models.logistic]
name = "logistic"
batch_size = 128
learning_rate = 0.001
seq_len = 256
weight_decay = 1e-5
num_categories = 83

[models.nn]
name = "nn"
batch_size = 128
learning_rate = 0.0005
seq_len = 256
weight_decay = 4e-1
num_categories = 83

[models.distil_bert]
name = "distil_bert"
pretrained = "distilbert-base-uncased"
batch_size = 32
learning_rate = 5e-5
max_length = 256                       # 512 is the max length for distilbert
num_categories = 83
